name: mc3_baselines
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.9, 3.6 original
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - scipy         # Common math/stats/science functions
    - pip
    - pip:
        - mc3
        - pykrige