name: mc3_baselines
channels:
    - defaults
dependencies:
    - python=3.6    # Python version 3.9, 3.6 original
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - pyjanitor       # Cleans up Pandas dataframe column names
    - scipy         # Common math/stats/science functions
    - seaborn       # Statistical visualizations
    - flake8
    - pep8
    - pip
    - pip:
        - mc3
        - pykrige
    - pathlib 